"use strict";

require("./Route/Admin/asset");
require("./Route/Admin/auth");
require("./Route/Admin/bonus");
require("./Route/Admin/currency");
require("./Route/Admin/demouser");
require("./Route/Admin/deposite");
require("./Route/Admin/faq");
require("./Route/Admin/help");
require("./Route/Admin/kyc");
require("./Route/Admin/language");
require("./Route/Admin/language_labels");
require("./Route/Admin/log");
require("./Route/Admin/news");
require("./Route/Admin/payment-gateway");
require("./Route/Admin/push-notification");
require("./Route/Admin/setting");
require("./Route/Admin/trade-history");
require("./Route/Admin/training");
require("./Route/Admin/admin");
require("./Route/Admin/widrow");
require("./Route/Admin/user");

require("./Route/demouser");
require("./Route/deposite");
require("./Route/kyc");
require("./Route/push-notification");
require("./Route/trade-history");
require("./Route/user");
require("./Route/widrow");
require("./Route/public");
